import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import AppProvider from "./context/AppProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <div
            style={{
              display: "grid",
              gridTemplateAreas: `
                "header header"
                "sidebar main"
              `,
              gridTemplateColumns: "200px 1fr",
              gridTemplateRows: "auto 1fr",
              height: "100vh",
            }}
          >
            <Header style={{ gridArea: "header" }} />
            <Sidebar style={{ gridArea: "sidebar" }} />
            <main style={{ gridArea: "main", padding: "1rem" }}>{children}</main>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}