import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import AppProvider from "./context/AppProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
        <Header />
        <main>
          <Sidebar />
          {children}
        </main>
        </AppProvider>
      </body>
    </html>
  );
}
